### ISSUE TITLE
Error downloading LD panel

### ISSUE THREAD

**Issue by biona001** [aaronsossin/gnomAD_LD_Easy_Querying#1]
I was at step 2 trying to download the African panel. 

From `gnomAD_LD_Easy_Querying/downloading_data_from_gnomAD` I executed
```
python3 run_download_script.py gs://gcp-public-data--gnomad/release/2.1.1/ld/gnomad.genomes.r2.1.1.afr.common.adj.ld.bm
```
And I got the following error in `gnomAD_LD_Easy_Querying/batch_script_files/error_files/error_download.txt`
```

The following have been reloaded with a version change:
  1) python/2.7.13 => python/3.6.1

/home/users/bbchu/.local/lib/python3.6/site-packages/OpenSSL/crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
Traceback (most recent call last):
  File "/home/users/bbchu/.local/bin/gsutil", line 5, in <module>
    from gslib.__main__ import main
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/__main__.py", line 94, in <module>
    from gslib.command_runner import CommandRunner
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/command_runner.py", line 37, in <module>
    from gslib.cloud_api_delegator import CloudApiDelegator
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/cloud_api_delegator.py", line 27, in <module>
    from gslib.cs_api_map import ApiMapConstants
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/cs_api_map.py", line 23, in <module>
    from gslib.gcs_json_api import GcsJsonApi
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/gcs_json_api.py", line 61, in <module>
    from gslib.gcs_json_credentials import SetUpJsonCredentialsAndCache
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/gcs_json_credentials.py", line 50, in <module>
    from gslib.utils.wrapped_credentials import WrappedCredentials
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/gslib/utils/wrapped_credentials.py", line 28, in <module>
    from google.auth import aws
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/aws.py", line 54, in <module>
    from google.auth import external_account
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/external_account.py", line 43, in <module>
    from google.auth import impersonated_credentials
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/impersonated_credentials.py", line 39, in <module>
    from google.auth import jwt
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/jwt.py", line 57, in <module>
    from google.auth import _service_account_info
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/crypt/__init__.py", line 43, in <module>
    from google.auth.crypt import rsa
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/crypt/rsa.py", line 20, in <module>
    from google.auth.crypt import _cryptography_rsa
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/google/auth/crypt/_cryptography_rsa.py", line 33, in <module>
    _BACKEND = backends.default_backend()
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py", line 8, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 132, in <module>
    class Backend:
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1190, in Backend
    def _handle_key_loading_error(self) -> typing.NoReturn:
AttributeError: module 'typing' has no attribute 'NoReturn'
```

**Comment by biona001** [comment]
Interestingly, I tried to manually download the file using `gsutils`, and when I executed (which supposedly allows one to browse gnomAD data?)
```
gsutil ls gs://gcp-public-data--gnomad/release/
```
in the command line, I get the same exact error. So maybe this is not an issue with your code?

**Comment by aaronsossin** [comment]
I believe this is a Python issue. Could you try loading Python3 with ml python/3.6.1 before running the script?

**Comment by biona001** [comment]
I tried
```
ml python/3.6.1
python3 run_download_script.py gs://gcp-public-data--gnomad/release/2.1.1/ld/gnomad.genomes.r2.1.1.afr.common.adj.ld.bm
```
and I get the same error in `gnomAD_LD_Easy_Querying/batch_script_files/error_files/error_download.txt`...

For now, I think I'll try to download the files myself, and then try the next module, which is probably more important than figuring out why automatic downloading isn't working..

**Comment by aaronsossin** [comment]
Sounds good @biona001. Will debug on my end in the meantime. 

One more idea: 
perhaps you need to 
<code> pip3 install gsutil </code>

before running the script.

**Comment by biona001** [comment]
@aaronsossin seems like that was the problem. Now the downloading script has been running for > 5 minutes. I'll keep you posted. Thanks you!
