### ISSUE TITLE
No such file or directory in step 3

### ISSUE THREAD

**Issue by biona001** [aaronsossin/gnomAD_LD_Easy_Querying#4]
In step 3, in directory `gnomAD_LD_Easy_Querying/generating_independent_partitions/`, I did
```
ml python/3.6.1
python3 run_retrieve_independent_blocks.py afr
```
and I got the following error in `gnomAD_LD_Easy_Querying/batch_script_files/error_files/error_retrieve_independent_blocks.txt`
```
Traceback (most recent call last):
  File "retrieve_independent_blocks.py", line 65, in <module>
    beriza_chromsome_and_population_partition_file_df = pd.read_csv(beriza_chromsome_and_population_partition_file,sep='\t')
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/users/bbchu/gnomAD_LD_Easy_Querying/generating_independent_blocks/ldetect-data/AFR/fourier_ls-chr3.bed'
```
I manually created the directory `generating_independent_blocks/ldetect-data/AFR` but I'm not sure where I can retrieve `fourier_ls-chr3.bed`...

**Comment by aaronsossin** [comment]
Thank you for this comment! The problem arose since it turns out ldetect-data is a github "submodule" and not a normal folder. So, instead of uploading the contents within ldetect-data, it just uploaded the github submodule link. **You will not have to manually create these directories**

Stay tuned for this to be resolved in next push

**Comment by aaronsossin** [comment]
Changed ldetect-data from a submodule to a normal folder. If you pull the current repo, should have all the files needed within "ldetect-data". 

Thank you!

**Comment by biona001** [comment]
@aaronsossin I am still getting the same error. Did you mean to put stuff in `ldetect-data` under `generating_independent_blocks`? On master it is under `generating_independent_partitions`
