### ISSUE TITLE
Missing CSV file in step 5

### ISSUE THREAD

**Issue by biona001** [aaronsossin/gnomAD_LD_Easy_Querying#6]
Under directory `generating_LD_matrices` I executed
```
python3 run_populate_LD_matrices.py afr
```
and I saw the following error in `batch_script_files/error_files/error_LD1.txt`
```
Traceback (most recent call last):
  File "populate_LD_matrices.py", line 235, in <module>
    final_df.to_csv(save_file,sep='\t')
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/users/bbchu/.local/lib/python3.6/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/users/bbchu/gnomAD_LD_Easy_Querying/LD_matrices/afr/1_248140280_249239381.csv'
```

**Comment by aaronsossin** [comment]
I suspect this is because the "/scratch/users/bbchu/gnomAD_LD_Easy_Querying/LD_matrices/afr/" folder was not automatically generated as it should have been. Should be a quick fix, stay tuned for next pull

**Comment by aaronsossin** [comment]
Should be resolved in latest commit! Thank you

**Comment by aaronsossin** [comment]
.
